# UNIVERSAL FUNCTIONS OF NUMPY

In [1]:
import numpy as np

## 1. NP.ARRAY

In [2]:
#1D Array
arr1 = np.array([1,2,3,4,5])
print(arr1)

#2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

#3D Array
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## 2. NP.ZEROS

In [3]:
#1D Array
arr1 = np.zeros(5)
print(arr1)

#2D Array
arr2 = np.zeros((2,3))
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


## 3. NP.ONES

In [4]:
#1D Array
arr1 = np.ones(5)
print(arr1)

#2D Array
arr2 = np.ones((2,3))
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


## 4. NP.ARANGE

In [5]:
# Creating a 1D array with elements from 0 to 3
arr1 = np.arange(4)
print(arr1)

# Creating a 1D array with elements from 1 to 9 with a step of 2
arr2 = np.arange(1,10,2)
print(arr2)

[0 1 2 3]
[1 3 5 7 9]


## 5. NP.RESIZE

In [6]:
# Creating a 1D array with elements from 0 to 3
arr = np.arange(4)
print("Orignal array is: ",arr)

# Resizing the above array in the shape of (2,3)
resizedd_arr = np.resize(arr,(2,3))
print("Resized array is: ",resizedd_arr)


Orignal array is:  [0 1 2 3]
Resized array is:  [[0 1 2]
 [3 0 1]]


## 6. NP.RESHAPE

In [7]:
# Creating a 1D array with elements from 0 to 3
arr = np.arange(4)
print("Original Array is :", arr)

# Reshaping the above array to shape (4, 1)
reshaped_arr = np.reshape(arr, (4, 1))
print("Reshaped Array is :", reshaped_arr)


Original Array is : [0 1 2 3]
Reshaped Array is : [[0]
 [1]
 [2]
 [3]]


## 7. NP.TRANSPOSE

In [8]:
# Creating a 2D Array
arr = np.array([[1,2,3],[4,5,6]])
print("orignal Array is: ",arr)

# transposing the above array
transposed_arr = np.transpose(arr)
print(transposed_arr)

orignal Array is:  [[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 8. NP.SPLIT

In [9]:
# Creating a 1D Array
arr = np.arange(1,7)
print("Orignal Array is: ",arr)

# Spliting the above array into three sub-arrays
split_arr = np.split(arr,[2,4])
print("Splited Array is ",split_arr)

Orignal Array is:  [1 2 3 4 5 6]
Splited Array is  [array([1, 2]), array([3, 4]), array([5, 6])]


## 9. NP.MEAN

In [10]:
# Creating a 1D Array
arr = np.arange(1,7)
print("Orignal Array is: ",arr)

# Calculating Mean of the above Array
mean = np.mean(arr)
print("Calculated mean is ",mean)

Orignal Array is:  [1 2 3 4 5 6]
Calculated mean is  3.5


## 10. NP.MEDIAN

In [11]:
# Creating a 1D Array
arr = np.arange(1,5)
print("Orignal Array is: ",arr)

# Calculating Median of the above Array
median = np.median(arr)
print("Calculated median is ",median)

Orignal Array is:  [1 2 3 4]
Calculated median is  2.5


## 11. NP.SORT

In [12]:
# Creating a 1D Array
arr = np.array([6,1,5,2,4,3])
print("Orignal Array is ", arr)

# Sorting the above Array
sorted_arr = np.sort(arr)
print("Sorted Array is :",sorted_arr)


Orignal Array is  [6 1 5 2 4 3]
Sorted Array is : [1 2 3 4 5 6]


## 12. NP.RANDOM.RAND

In [13]:
# Generating a random numbers in shape of (2,3)
rand_number = np.random.rand(2,3)
print(rand_number)

[[0.82526152 0.31920369 0.87036566]
 [0.66067803 0.60019873 0.64112111]]


## 13. NP.RANDOM.RANDN

In [14]:
# Generating a random numbers in shape of (2,3)
randn_number = np.random.randn(2,3)
print(randn_number)

[[ 0.99456731 -0.76317945 -0.44740389]
 [-0.06164296 -0.65043953 -1.79708319]]


## 14. NP.RANDOM.RANDINT

In [15]:
# Generating a random numbers in shape of (2,3)
randint_number = np.random.randint(1,5,(2,3))
print(randint_number)

[[2 2 4]
 [3 3 4]]


## 15. NP.EYE

In [16]:
# Creating a identity matrix of shape (3,3)
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 16. NP.CONCATENATE

In [17]:
# Creating 2 different Arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6]])

# Concatenating Above two arrays along with axis=0
concatenated = np.concatenate((arr1,arr2),axis=0)
print(concatenated)

[[1 2]
 [3 4]
 [5 6]]


## 17. NP.LINSPACE

In [18]:
# Generating an array with equally spaced values
linspaced_arr = np.linspace(0,1,5)
print(linspaced_arr)

[0.   0.25 0.5  0.75 1.  ]


## 18. NP.RAVEL

In [19]:
# Creating a 2D Array
arr = np.array([[1,2,3],[4,5,6]])

# Flattening the above array to 1D
flattened_arr = np.ravel(arr)
print(flattened_arr)

[1 2 3 4 5 6]


## 19. NP.ADD

In [20]:
# Creating 2 Arrays
arr1  = np.array([1,2,3])
arr2 = np.array([3,4,5])

# Adding the above 2 Arrays
added_arr = np.add(arr1,arr2)
print(added_arr)

[4 6 8]


## 20.  NP.UNIQUE

In [21]:
# Creating a 1D array with duplicate values
arr = np.array([1,2,2,3,4,4,4,5,5,6])

# Performing Unique function on above Array
unique_arr = np.unique(arr)
print(unique_arr)

[1 2 3 4 5 6]
